install.packages('pacman')
library('pacman')

p_load('mice','VIM','HotDeckImputation','hot.deck')

data("airquality")
data <- airquality
data$Month <- as.factor(data$Month)
data$Day <- as.factor(data$Day)

#We are remove few values in a separate dataset so that we can compare our imputation effectiveness later by comparing with the original 
data[4:10,3] <- rep(NA,7)  ## replicate values of NA 7 times
data[1:5,4] <- NA


#What are missing values?


#What is the motivation of handling missing values?










#How to check for missing values multiple patterns of missing values in a dataset?
"""
There are two types of missing data:

MCAR: missing completely at random. This is the desirable scenario in case of missing data.
MNAR: missing not at random. Missing not at random data is a more serious issue and in this case it might be wise to check the data gathering process further and try to understand why the information is missing. For instance, if most of the people in a survey did not answer a certain question, why did they do that? Was the question unclear?

"""

summary(data)
all(complete.cases(data))

library('mice')
md.pattern(data[,-c(5,6)])
##The output tells us that 104 samples are complete, 34 samples miss only the Ozone measurement, 4 samples miss only the Solar.R value and so on.
##A perhaps more helpful visual representation can be obtained using the VIM package as follows

library('VIM')
aggr_plot <- aggr(data, col=c('navyblue','red'), numbers=TRUE, sortVars=TRUE, labels=names(data), cex.axis=.7, gap=3, ylab=c("Histogram of missing data","Pattern"))
## As we can see plot on the right hand side shows bottom to top the increasing number of missingness


marginplot(data[c(1,2)])
## red boxplot for a particular axis is the distribution for the scenarios where perpendicular axis values are missing
#If our assumption of MCAR data is correct, then we expect the red and blue box plots to be very similar.


# Q What are multiple type of techniques to impute missing values?

#Deletion based methods
"""## complete case analysis or listwise deletion

This is the simplest way to handle missing values where only those cases with no missing
values are considered 

Pros - if the missing pattern is MCAR, then the estimates will not be biased
COns - if the missing attern is not MCAR, then the estimates will be biased

"""
lr_model1 <- lm(Wind~.,data = data)
summary(lr_model1)

complete_cases = data[complete.cases(data),]
lr_model2 <- lm(Wind~.,data = complete_cases)
summary(lr_model2)
## Note lm has this feature as na.omit and na.exclude both do casewise deletion with respect to both predictors and criterions.


#Comapring above 2 models, There seems to be no difference in the models since the data is following MCAR


### Available case method or pairwise deletion
#This method uses only the data which is available
cov(data[,-c(5,6)])
cov(complete_cases)
cov(data[,-c(5,6)], use = "complete.obs")

## cons of this method when correlations are computed using different cases,
#the resulting patterns can be ones that are impossible to produce with complete data and eventually incorrect statistics

##Single Imputation Methods
###Mean/mode substitution
# computing the mean column wise and replacing the NA values in the column with mean/median based on the data distribution
##this might distort the distribution of the data by making it more peaked around mean and thereby reducing variance
## this will provide biased estimates inspite of the type of missingness
install.packages('HotDeckImputation')
library(HotDeckImputation)

imputed_data <- impute.mean(as.matrix(data))


###Regression Imputation
##missing values are replaced by a predicted score generated by a regression model based on the non-missing data
# lm() and predict() functions one by one taking one variable at a time

###Hot Deck Imputation
##This method sorts respondents and non-respondents into a number of imputation subsets according to a user-specied set of covariates
## Missing values are replaced with values from matching respondents that are similar wrt to covariates
## its based on the research here by https://www.researchgate.net/profile/Dieter_Joenssen
imputed_data <- impute.NN_HD(as.matrix(data[,-c(5:6)]),distance="man")
out <- hot.deck(data[,-c(5,6)])
hd2amelia(out)


###k-Nearest Neighbor Imputation
# This method is quite effective and simple
##The advantage of the knn approach is that it assumes data are missing at random (MAR) meaning,
#missing data only depends on the observed data; which in turn means, the knn approach is able to 
#take advantage of multivariate relationships in the completed data
##The disadvantage of this approach is it does not include a component to model random variation;
#consequently uncertainty in the imputed value is underestimated
p_load('DMwR')
knnImputation(data,k=2)
## try yaimpute package as well
p_load("VIM")
kNN(data, k=3)


##Model-Based Methods
###Maximum Likelihood
#The maximum likelihood method (implemented in R by the package mvnmle) is concerned only with a
#complete variance/covariance matrix based on maximum likelihood values from the available data
p_load(mvnmle)
cov(data[,-c(5,6)])
mlest(data[,-c(5,6)],iterlim = 150)


###Multiple imputation
